apiVersion: v1
kind: Service
metadata:
  name: frontend-healthmed-service # Name of the service
spec:
  selector:
    app: frontend-healthmed # Label selector to target pods with this label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Type of service (other options include ClusterIP, LoadBalancer, etc.)
